
variables:
  project: shared-resources

stages:
  - stage: validate
    displayName: Validate
    variables:
      - group: Development
    jobs:
      - template: pipelines/jobs/terraform/validate.yml

  - stage: plan_dev
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    displayName: Plan for development
    variables:
      - group: Development

    jobs:
      - template: pipelines/jobs/terraform/plan.yml
        parameters:
          workspace: dev

  - stage: 'Test'
    displayName: 'Deploy Test environment'
    variables:
      - group: Development

    jobs:
      - template: pipelines/jobs/terraform/apply.yml
        parameters:
          project: ${{ variables.project }}
          workspace: test
 
  - stage: 'Staging'
    displayName: 'Deploy Staging environment'
    variables:
      - group: Development

    jobs:
      - template: pipelines/jobs/terraform/apply.yml
        parameters:
          project: ${{ variables.project }}
          workspace: staging
