
variables:
  project: infru

stages:
  - stage: validate
    displayName: Validate
    variables:
      - group: Development
    jobs:
      - template: pipelines/jobs/terraform/validate.yml

  - stage: plan_dev
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    displayName: Сreate an execution plan for DEV environment
    variables:
      - group: Development

    jobs:
      - template: pipelines/jobs/terraform/plan.yml
        parameters:
          workspace: dev

  - stage: 'Dev'
    displayName: 'Deploy Dev environment'
    variables:
      - group: Development

    jobs:
      - template: pipelines/jobs/terraform/apply.yml
        parameters:
          project: ${{ variables.project }}
          workspace: dev

  - stage: plan_test
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    displayName: Сreate an execution plan for TEST environment
    variables:
      - group: Development

    jobs:
      - template: pipelines/jobs/terraform/plan.yml
        parameters:
          workspace: test

  - stage: 'Test'
    displayName: 'Deploy Test environment'
    variables:
      - group: Development

    jobs:
      - template: pipelines/jobs/terraform/apply.yml
        parameters:
          project: ${{ variables.project }}
          workspace: test
 
 
  - stage: plan_staging
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    displayName: Сreate an execution plan for STAGE environment
    variables:
      - group: Development

    jobs:
      - template: pipelines/jobs/terraform/plan.yml
        parameters:
          workspace: stage
 
  - stage: 'Stage'
    displayName: 'Deploy Stage environment'
    variables:
      - group: Development

    jobs:
      - template: pipelines/jobs/terraform/apply.yml
        parameters:
          project: ${{ variables.project }}
          workspace: stage
